services:
  postgres:
    image: postgres:latest
    container_name: database_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Brenno1234567
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"   
    volumes:
      - redis-data:/data 
    environment:
      - REDIS_PASSWORD=Brenno123456789 

volumes:
  redis-data:  
  postgres_data: